steps:
#  - name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  #    id: build
  #    args: ["-DskipTests=true", "package","appengine:deploy"]
  #timeout: "1600s"
  #  - name: "gcr.io/cloud-builders/gcloud"
  #    args: ["app", "deploy"]
  #timeout: "1600s"
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']