steps:
  #  - name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  #    id: build
  #    args: ["-DskipTests=true", "package","appengine:deploy"]
  #timeout: "1600s"
  #  - name: "gcr.io/cloud-builders/gcloud"
  #    args: ["app", "deploy"]
  #timeout: "1600s"
  #  - name: 'gcr.io/cloud-builders/mvn'
  #    args: ['install']
  #  - name: 'gcr.io/cloud-builders/gcloud'
  #    args: ['app', 'deploy']

  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/inventorymanagement", "--build-arg=JAR_FILE=target/inventorymanagement-1.0.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/inventorymanagement"]